export interface PublicRoute {
  path: string;
  title: string;
  description: string;
  status: 200 | 404;
  published?: boolean;
  category?: 'public' | 'feature' | 'use-case' | 'comparison' | 'account' | 'legal';
  competitor?: string;
}

const routeDefinitions: Array<
  [
    string,
    string,
    string,
    NonNullable<PublicRoute['category']>,
    boolean | undefined,
    string | undefined,
  ]
> = [
  [
    '/',
    'Build with the model you want.',
    'Astra AI is a desktop coding agent for local projects, bounded actions, and verified results.',
    'public',
    true,
    undefined,
  ],
  [
    '/pricing',
    'Astra AI pricing',
    'Server-controlled plans with predictable credit-based usage.',
    'public',
    true,
    undefined,
  ],
  [
    '/download',
    'Download Astra AI',
    'Install the supported Windows desktop application and review release requirements.',
    'public',
    true,
    undefined,
  ],
  [
    '/download/windows',
    'Astra AI for Windows',
    'Windows 10/11 x64 download details, release notes, and integrity information.',
    'public',
    true,
    undefined,
  ],
  [
    '/models',
    'Choose the model for the job',
    'See the models Astra AI has approved and how Auto selects among them.',
    'public',
    true,
    undefined,
  ],
  [
    '/security',
    'Security boundaries you can inspect',
    'Workspace confinement, capability permissions, bounded actions, and secret-aware handling.',
    'public',
    true,
    undefined,
  ],
  [
    '/docs',
    'Astra AI documentation',
    'Learn how local workspaces, permissions, verification, and model usage work.',
    'public',
    true,
    undefined,
  ],
  [
    '/blog',
    'Astra AI notes',
    'Practical writing about agentic development, verification, and product updates.',
    'public',
    true,
    undefined,
  ],
  [
    '/features/agent',
    'A coding agent with a finish line',
    'Ask, plan, inspect, edit, run, verify, and review the resulting diff.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/codebase',
    'Understand the codebase before changing it',
    'Relevant-file search and scoped local reads keep the agent grounded in the repository.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/model-switching',
    'Switch models without rebuilding your workflow',
    'Use approved models through one server-controlled catalog and a shared task history.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/task-estimation',
    'See an estimate before a large task starts',
    'Task budgets and cost estimates help prevent an accidental open-ended run.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/mcp',
    'Connect tools with visible boundaries',
    'Use MCP only where a scoped connection and its permissions make sense.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/remote',
    'Remote control where supported',
    'Use the existing pairing and relay boundary without implying unrestricted public execution.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/security',
    'Security-aware development',
    'Workspace paths, command risk, approvals, rollback, and redaction are part of the workflow.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/cost-control',
    'Keep model usage bounded',
    'Reservations, task budgets, actual usage receipts, and settlement records work together.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/learn',
    'Learn from the project you actually opened',
    'Get explanations grounded in files, functions, and the local repository.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/viva',
    'Practice the architecture you built',
    'Viva questions reference project elements instead of generic computer-science prompts.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/hackathon',
    'Turn a brief into a credible MVP',
    'Define must-have scope, implement it, verify it, and prepare the demo story.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/skills',
    'Relevant Skills, loaded on demand',
    'Workflow packages guide tasks without injecting every instruction into every model request.',
    'feature',
    true,
    undefined,
  ],
  [
    '/features/plugins',
    'Extensions with explicit permissions',
    'Extend Astra only through declared capabilities and reviewable trust boundaries.',
    'feature',
    true,
    undefined,
  ],
  [
    '/use-cases/students',
    'Astra AI for students',
    'Build projects, understand the code, and prepare for interviews from one desktop workflow.',
    'use-case',
    true,
    undefined,
  ],
  [
    '/use-cases/freelancers',
    'Astra AI for freelancers',
    'Move from brief to verified change while keeping model and tool costs visible.',
    'use-case',
    true,
    undefined,
  ],
  [
    '/use-cases/startups',
    'Astra AI for startups',
    'Keep a small team moving across unfamiliar code without hiding the resulting diff.',
    'use-case',
    true,
    undefined,
  ],
  [
    '/use-cases/developers',
    'Astra AI for developers',
    'A local-first agent for real repositories, real commands, and real verification.',
    'use-case',
    true,
    undefined,
  ],
  [
    '/use-cases/teams',
    'Astra AI for teams',
    'Server-controlled models, plans, costs, and an auditable execution boundary.',
    'use-case',
    true,
    undefined,
  ],
  [
    '/compare',
    'Compare coding-agent workflows',
    'A factual comparison hub. Individual pages are published only when their sources are current and verified.',
    'comparison',
    true,
    undefined,
  ],
  [
    '/compare/cursor',
    'Astra AI vs Cursor',
    'Compare model access, usage economics, workspace workflow, and agent boundaries with current official sources.',
    'comparison',
    true,
    'cursor',
  ],
  [
    '/compare/kiro',
    'Astra AI vs Kiro',
    'Compare local desktop work, model credits, web workflows, and plan structure with current official sources.',
    'comparison',
    true,
    'kiro',
  ],
  [
    '/compare/kilo-code',
    'Astra AI vs Kilo Code',
    'Compare managed credits, BYOK flexibility, extensions, and cloud compute with current official sources.',
    'comparison',
    true,
    'kilo-code',
  ],
  [
    '/compare/cline',
    'Astra AI vs Cline',
    'Compare a managed desktop product with an open-source, provider-flexible coding agent.',
    'comparison',
    true,
    'cline',
  ],
  [
    '/compare/windsurf',
    'Astra AI vs Windsurf',
    'Comparison pending a current official Windsurf product source.',
    'comparison',
    false,
    'windsurf',
  ],
  [
    '/compare/roo-code',
    'Astra AI vs Roo Code',
    'Comparison pending a current official Roo Code product source.',
    'comparison',
    false,
    'roo-code',
  ],
  [
    '/compare/github-copilot',
    'Astra AI vs GitHub Copilot',
    'Compare a desktop-first local agent with GitHub’s editor, CLI, and cloud-agent ecosystem.',
    'comparison',
    true,
    'github-copilot',
  ],
  [
    '/compare/byok',
    'Astra AI vs BYOK agents',
    'Understand managed model access and BYOK control without treating either approach as universally better.',
    'comparison',
    true,
    'byok',
  ],
  [
    '/alternatives/cursor',
    'Astra AI alternative to Cursor',
    'A use-case-focused comparison for developers considering a managed multi-model desktop workflow.',
    'comparison',
    true,
    'cursor',
  ],
  [
    '/alternatives/kiro',
    'Astra AI alternative to Kiro',
    'Compare a local Windows workflow with Kiro’s current documented surfaces.',
    'comparison',
    true,
    'kiro',
  ],
  [
    '/alternatives/cline',
    'Astra AI alternative to Cline',
    'Compare managed credits and onboarding with a provider-flexible open-source agent.',
    'comparison',
    true,
    'cline',
  ],
  [
    '/alternatives/windsurf',
    'Astra AI alternative to Windsurf',
    'Comparison pending a current official Windsurf product source.',
    'comparison',
    false,
    'windsurf',
  ],
  [
    '/marketplace',
    'Astra AI marketplace',
    'Discover reviewed Skills, Plugins, and MCP packages when publishing is enabled.',
    'public',
    false,
    undefined,
  ],
  [
    '/skills',
    'Astra AI Skills',
    'Browse workflow packages with publisher, version, license, and permission details.',
    'public',
    true,
    undefined,
  ],
  [
    '/plugins',
    'Astra AI Plugins',
    'Browse capability-scoped extensions without granting unrestricted access by default.',
    'public',
    true,
    undefined,
  ],
  [
    '/mcp',
    'Astra AI MCP directory',
    'Browse scoped MCP connection definitions and their capabilities.',
    'public',
    true,
    undefined,
  ],
  [
    '/changelog',
    'Astra AI changelog',
    'Read versioned Astra AI product and release notes.',
    'public',
    true,
    undefined,
  ],
  // Legacy public paths remain resolvable while the canonical Astra routes take over.
  [
    '/students',
    'Astra AI for students',
    'Build projects, understand the code, and prepare for interviews from one desktop workflow.',
    'use-case',
    false,
    undefined,
  ],
  [
    '/vibe-coding',
    'Vibe coding with Astra AI',
    'Turn an idea into a working project while keeping changes bounded and verifiable.',
    'feature',
    false,
    undefined,
  ],
  [
    '/ai-coding-agent',
    'Astra AI coding agent',
    'A local repository agent that can inspect, edit, run, test, and show a verified diff.',
    'feature',
    false,
    undefined,
  ],
  [
    '/compare/lyntar-vs-cursor',
    'Astra AI vs Cursor',
    'Legacy alias for the current Astra AI versus Cursor comparison.',
    'comparison',
    false,
    'cursor',
  ],
  [
    '/compare/lyntar-vs-github-copilot',
    'Astra AI vs GitHub Copilot',
    'Legacy alias for the current Astra AI versus GitHub Copilot comparison.',
    'comparison',
    false,
    'github-copilot',
  ],
  [
    '/compare/lyntar-vs-cline',
    'Astra AI vs Cline',
    'Legacy alias for the current Astra AI versus Cline comparison.',
    'comparison',
    false,
    'cline',
  ],
  [
    '/compare/lyntar-vs-windsurf',
    'Astra AI vs Windsurf',
    'Legacy alias for a comparison pending a current official Windsurf product source.',
    'comparison',
    false,
    'windsurf',
  ],
  [
    '/login',
    'Sign in to Astra AI',
    'Use one Astra identity across the website, desktop, billing, and devices.',
    'account',
    true,
    undefined,
  ],
  [
    '/signup',
    'Create your Astra AI account',
    'Create an account and verify your email before using the product.',
    'account',
    true,
    undefined,
  ],
  [
    '/verify-email',
    'Verify your Astra AI email',
    'Enter the one-time verification code sent to your email.',
    'account',
    true,
    undefined,
  ],
  [
    '/forgot-password',
    'Reset your Astra AI password',
    'Request a time-limited password reset link.',
    'account',
    true,
    undefined,
  ],
  [
    '/reset-password',
    'Choose a new Astra AI password',
    'Set a new password after verifying a reset request.',
    'account',
    true,
    undefined,
  ],
  [
    '/account',
    'Your Astra AI account',
    'Manage your profile, security, plan, and product preferences.',
    'account',
    true,
    undefined,
  ],
  [
    '/account/wallet',
    'Your Astra AI credits',
    'View server-reported balance, reservations, settlements, and usage.',
    'account',
    true,
    undefined,
  ],
  [
    '/account/billing',
    'Astra AI billing',
    'Manage authoritative plan and payment state.',
    'account',
    true,
    undefined,
  ],
  [
    '/account/devices',
    'Your Astra AI devices',
    'Review and revoke active desktop sessions.',
    'account',
    true,
    undefined,
  ],
  [
    '/privacy',
    'Astra AI privacy',
    'How account, usage, and local workspace metadata are handled.',
    'legal',
    true,
    undefined,
  ],
  [
    '/terms',
    'Astra AI terms',
    'Terms for using Astra AI services and software.',
    'legal',
    true,
    undefined,
  ],
  [
    '/refund-policy',
    'Astra AI refund policy',
    'Refund and payment policy information.',
    'legal',
    true,
    undefined,
  ],
  [
    '/open-source-notices',
    'Astra AI open-source notices',
    'Third-party dependency and license notices.',
    'legal',
    true,
    undefined,
  ],
];

export const publicRoutes: PublicRoute[] = routeDefinitions.map(
  ([path, title, description, category, published, competitor]) => ({
    path,
    title,
    description,
    status: 200,
    category,
    ...(published === undefined ? {} : { published }),
    ...(competitor === undefined ? {} : { competitor }),
  }),
);

export function resolvePublicRoute(pathname: string): PublicRoute {
  return (
    publicRoutes.find((route) => route.path === pathname) ?? {
      path: pathname,
      title: 'Page not found',
      description: 'This route is not part of the Astra AI public surface.',
      status: 404,
    }
  );
}

export interface PublicPlanCard {
  id: string;
  displayName: string;
  priceInr: string;
  monthlyCredits: string;
  seats: number;
  activeJobsPerSeat: number;
  pooledCredits: boolean;
  topUpEnabled: boolean;
  taxExclusive: boolean;
  source: 'server' | 'unavailable';
}

export const noLivePlanData = 'NO_LIVE_DATA';
